numbers=list(range(1,12))
len_numbers=int(len(numbers))
print(f"The first three items in the list are:{numbers[0:3]}")
print(f"Three items from the middle of the list are:{numbers[len_numbers//2-1:len_numbers//2+2]}")
print(f"The last three items in the list are:{numbers[-3:]}")