PRAGMA foreign_keys = OFF;

DROP TABLE IF EXISTS [Message];
DROP TABLE IF EXISTS [Courseware];
DROP TABLE IF EXISTS [Score];
DROP TABLE IF EXISTS [CourseSelection];
DROP TABLE IF EXISTS [CoursePrerequisite];
DROP TABLE IF EXISTS [Course];
DROP TABLE IF EXISTS [User];
DROP TABLE IF EXISTS [Teacher];
DROP TABLE IF EXISTS [Student];
DROP TABLE IF EXISTS [College];

PRAGMA foreign_keys = ON;

CREATE TABLE [College]
(
    [COLLEGEID] TEXT NOT NULL PRIMARY KEY,
    [COLLEGENAME] TEXT NOT NULL
);

CREATE TABLE [Student]
(
    [SNO] TEXT NOT NULL PRIMARY KEY,
    [SNAME] TEXT NOT NULL,
    [SSEX] TEXT NOT NULL,
    [SAGE] INTEGER NOT NULL,
    [SDEPT] TEXT NOT NULL,
    [COLLEGEID] TEXT NOT NULL,

    FOREIGN KEY ([COLLEGEID]) REFERENCES [College]([COLLEGEID])
);

CREATE TABLE [Teacher]
(
    [TNO] TEXT NOT NULL PRIMARY KEY,
    [TNAME] TEXT NOT NULL,
    [TSEX] TEXT NOT NULL,
    [TDEPT] TEXT NOT NULL,
    [COLLEGEID] TEXT NOT NULL,

    FOREIGN KEY ([COLLEGEID]) REFERENCES [College]([COLLEGEID])
);

CREATE TABLE [User]
(
    [USERID] TEXT NOT NULL PRIMARY KEY,
    [ACCOUNT] TEXT NOT NULL UNIQUE,
    [PASSWORDHASH] TEXT NOT NULL,
    [ROLE] INTEGER NOT NULL,
    [RELATEDID] TEXT NULL,
    [COLLEGEID] TEXT NULL
);

CREATE TABLE [Course]
(
    [CNO] TEXT NOT NULL PRIMARY KEY,
    [CNAME] TEXT NOT NULL,
    [CTIME] INTEGER NOT NULL,
    [CCREDIT] REAL NOT NULL,
    [TNO] TEXT NOT NULL,
    [COLLEGEID] TEXT NOT NULL,
    [INTRODUCTION] TEXT NULL,
    [CAPACITY] INTEGER NOT NULL,
    [ISOPEN] INTEGER NOT NULL,

    FOREIGN KEY ([TNO]) REFERENCES [Teacher]([TNO]),
    FOREIGN KEY ([COLLEGEID]) REFERENCES [College]([COLLEGEID])
);

CREATE TABLE [CoursePrerequisite]
(
    [ID] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    [CNO] TEXT NOT NULL,
    [PREREQUISITECNO] TEXT NOT NULL,

    FOREIGN KEY ([CNO]) REFERENCES [Course]([CNO]),
    FOREIGN KEY ([PREREQUISITECNO]) REFERENCES [Course]([CNO])
);

CREATE TABLE [CourseSelection]
(
    [ID] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    [SNO] TEXT NOT NULL,
    [CNO] TEXT NOT NULL,
    [STATUS] INTEGER NOT NULL,
    [SELECTEDAT] TEXT NOT NULL,

    FOREIGN KEY ([SNO]) REFERENCES [Student]([SNO]),
    FOREIGN KEY ([CNO]) REFERENCES [Course]([CNO]),

    UNIQUE ([SNO], [CNO])
);

CREATE TABLE [Score]
(
    [ID] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    [SNO] TEXT NOT NULL,
    [CNO] TEXT NOT NULL,
    [GRADE] INTEGER NOT NULL,
    [RECORDEDAT] TEXT NOT NULL,

    FOREIGN KEY ([SNO]) REFERENCES [Student]([SNO]),
    FOREIGN KEY ([CNO]) REFERENCES [Course]([CNO]),

    UNIQUE ([SNO], [CNO]),

    CHECK ([GRADE] >= 0 AND [GRADE] <= 100)
);

CREATE TABLE [Courseware]
(
    [ID] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    [CNO] TEXT NOT NULL,
    [FILENAME] TEXT NOT NULL,
    [FILEPATH] TEXT NOT NULL,
    [UPLOADEDBY] TEXT NOT NULL,
    [UPLOADEDAT] TEXT NOT NULL,

    FOREIGN KEY ([CNO]) REFERENCES [Course]([CNO]),
    FOREIGN KEY ([UPLOADEDBY]) REFERENCES [Teacher]([TNO])
);

CREATE TABLE [Message]
(
    [ID] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    [FROMUSERID] TEXT NOT NULL,
    [TOUSERID] TEXT NOT NULL,
    [CONTENT] TEXT NOT NULL,
    [CREATEDAT] TEXT NOT NULL,
    [ISREAD] INTEGER NOT NULL,

    FOREIGN KEY ([FROMUSERID]) REFERENCES [User]([USERID]),
    FOREIGN KEY ([TOUSERID]) REFERENCES [User]([USERID])
);
