set_property IOSTANDARD LVCMOS18 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {seg[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sel[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sel[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sel[0]}]
set_property PACKAGE_PIN P16 [get_ports {seg[6]}]
set_property PACKAGE_PIN P17 [get_ports {seg[5]}]
set_property PACKAGE_PIN N17 [get_ports {seg[4]}]
set_property PACKAGE_PIN N15 [get_ports {seg[3]}]
set_property PACKAGE_PIN M15 [get_ports {seg[2]}]
set_property PACKAGE_PIN L17 [get_ports {seg[1]}]
set_property PACKAGE_PIN L18 [get_ports {seg[0]}]
set_property PACKAGE_PIN N20 [get_ports {sel[2]}]
set_property PACKAGE_PIN P21 [get_ports {sel[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports rst_n]
set_property PACKAGE_PIN Y8 [get_ports clk]
set_property PACKAGE_PIN P15 [get_ports rst_n]

# 设置时钟类型！！！
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk]

set_property PACKAGE_PIN L22 [get_ports {sel[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports {pos[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {pos[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {pos[0]}]
set_property PACKAGE_PIN L22 [get_ports {pos[0]}]
set_property PACKAGE_PIN P21 [get_ports {pos[1]}]
set_property PACKAGE_PIN N20 [get_ports {pos[2]}]
