set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk]

set_property IOSTANDARD LVCMOS18 [get_ports {row_data[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {row_data[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {row_data[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {row_data[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {row_data[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {row_data[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {row_data[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {row_data[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {row_data[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {row_data[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {row_data[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {row_data[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {row_data[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {row_data[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {row_data[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {row_data[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports common_anode]
set_property IOSTANDARD LVCMOS18 [get_ports rst]



set_property PACKAGE_PIN Y8 [get_ports clk]
set_property PACKAGE_PIN P15 [get_ports rst]
set_property PACKAGE_PIN AB14 [get_ports {row_data[0]}]
set_property PACKAGE_PIN W16 [get_ports {row_data[1]}]
set_property PACKAGE_PIN U17 [get_ports {row_data[2]}]
set_property PACKAGE_PIN U15 [get_ports {row_data[3]}]
set_property PACKAGE_PIN W15 [get_ports {row_data[4]}]
set_property PACKAGE_PIN Y14 [get_ports {row_data[5]}]
set_property PACKAGE_PIN V14 [get_ports {row_data[6]}]
set_property PACKAGE_PIN V13 [get_ports {row_data[7]}]
set_property PACKAGE_PIN T16 [get_ports {row_data[8]}]
set_property PACKAGE_PIN M19 [get_ports {row_data[9]}]
set_property PACKAGE_PIN N19 [get_ports {row_data[10]}]
set_property PACKAGE_PIN P20 [get_ports {row_data[11]}]
set_property PACKAGE_PIN L21 [get_ports {row_data[12]}]
set_property PACKAGE_PIN M21 [get_ports {row_data[13]}]
set_property PACKAGE_PIN W17 [get_ports {row_data[14]}]
set_property PACKAGE_PIN AA16 [get_ports {row_data[15]}]

set_property PACKAGE_PIN N18 [get_ports common_anode]



set_property IOSTANDARD LVCMOS18 [get_ports {row_idx[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {row_idx[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {row_idx[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {row_idx[0]}]
set_property PACKAGE_PIN AB17 [get_ports {row_idx[3]}]
set_property PACKAGE_PIN W18 [get_ports {row_idx[2]}]
set_property PACKAGE_PIN AB16 [get_ports {row_idx[1]}]
set_property PACKAGE_PIN AB15 [get_ports {row_idx[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports {char_index[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {char_index[0]}]

set_property PACKAGE_PIN V10 [get_ports {char_index[1]}]
set_property PACKAGE_PIN AA9 [get_ports {char_index[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports auto_mode]
set_property PACKAGE_PIN Y11 [get_ports auto_mode]
